package io.github.archunit;

import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaClass;

import static com.tngtech.archunit.base.DescribedPredicate.describe;

public class ImmutablesTestPredicates {

	public static final DescribedPredicate<JavaClass> ARE_NOT_GENERATED = describe(
			"are not generated by Immutables library",
			clazz -> !clazz.getSimpleName().isEmpty()
					&& !clazz.getSimpleName().startsWith("Immutable")
					&& !clazz.getSimpleName().equals("Builder"));

}
